name: BingoReloaded # the plugins name as it should appear in the plugin list /pl
version: 1.2.0 # the plugin's version
author: Steven
main: me.steven.bingoreloaded.BingoReloaded
api-version: 1.19

permissions:
  bingo.admin:
    description: Bingo admins can create and start games of Bingo, as well as edit game settings in the /bingo menu
    default: op

commands:
  bingo:
    description: Used to open the settings menu as well as to start and end the game.
  card:
    description: Used to edit and create cards containing itemlists where each list as it's own frequency.
  itemlist:
    description: Used to edit and create lists containing items to be used in bingo cards.
  btc:
    description: Used to toggle team chat when a game is active